// Package changelogpr implements the changelogpr Publisher, which maintains a
// single marker-keyed CHANGELOG.md pull-request per release. The PR is created
// on the deterministic branch cadoo/changelog/vX.Y.Z and updated in place on
// re-runs (idempotent; D-13/D-14). A hidden HTML marker in the PR body is the
// single source of truth for the already-exists check, mirroring the
// postSummary read-back pattern in internal/orchestrator/reviewer.go.
//
// When the provider does not implement vcs.BranchCommitter, Publish logs a
// warning and returns nil (graceful degradation, D-15). When reading back the
// existing CHANGELOG.md fails, Publish logs and proceeds best-effort rather
// than failing the run (mirrors ci.go priorStore degrade).
package changelogpr

import (
	"context"
	"log/slog"

	"github.com/payamqorbanpour/cadoo/internal/releasedocs"
	"github.com/payamqorbanpour/cadoo/internal/vcs"
)

const (
	// changelogPath is the canonical path for the CHANGELOG file in a repository.
	changelogPath = "CHANGELOG.md"
	// commitMessage is the deterministic commit message used when upserting
	// CHANGELOG.md on the publisher branch.
	commitMessage = "chore: update CHANGELOG.md via Cadoo"
	// prBase is the base branch for the changelog PR. "main" is the most common
	// default; providers that need a different default can be overridden in the
	// config (Phase 2).
	prBase = "main"
)

// Publisher delivers changelog artifact content by maintaining a single
// CHANGELOG.md pull-request on a deterministic branch per release. It
// implements releasedocs.Publisher and is safe for concurrent use.
type Publisher struct{}

// Target returns TargetChangelogPR, identifying where this publisher writes.
func (Publisher) Target() releasedocs.PublishTarget {
	return releasedocs.TargetChangelogPR
}

// Publish ensures exactly one CHANGELOG.md PR exists for rc.ToRef. It writes
// the changelog artifact to CHANGELOG.md on the deterministic branch
// releasedocs.ChangelogBranch(rc.ToRef) and opens or updates a PR whose body
// contains the hidden marker releasedocs.ChangelogMarker(rc.ToRef). The PR is
// identified on re-runs via the hidden marker + deterministic branch (D-13).
//
// If rc.Provider does not implement vcs.BranchCommitter the call is skipped
// with a warning log and nil is returned (D-15). If reading back the existing
// CHANGELOG.md fails, Publish logs a warning and proceeds best-effort (may
// prepend a duplicate section this run) rather than failing — mirrors
// ci.go priorStore degrade shape.
func (Publisher) Publish(ctx context.Context, rc releasedocs.ReleaseContext, arts []releasedocs.Artifact) error {
	bc, ok := rc.Provider.(vcs.BranchCommitter)
	if !ok {
		slog.Warn("BranchCommitter capability absent; skipping changelogpr",
			"provider", rc.Provider.Kind(),
			"repo", rc.Repo,
		)
		return nil
	}

	// Find the changelog artifact.
	var newSection string
	for _, a := range arts {
		if a.Kind == releasedocs.KindChangelog {
			newSection = string(a.Content)
			break
		}
	}
	// No changelog artifact in this run — nothing to publish.
	if newSection == "" {
		return nil
	}

	branch := releasedocs.ChangelogBranch(rc.ToRef)
	marker := releasedocs.ChangelogMarker(rc.ToRef)

	// Read the existing CHANGELOG.md from the branch or ToRef. On failure,
	// proceed best-effort (may result in a duplicate section this run) — mirrors
	// ci.go priorStore degrade shape.
	existing := ""
	if ff, ok := rc.Provider.(releasedocs.FileFetcher); ok {
		raw, err := ff.FetchFileFromRef(ctx, rc.Repo, rc.ToRef, changelogPath)
		if err != nil {
			slog.Warn("changelogpr: FetchFileFromRef failed; proceeding best-effort",
				"repo", rc.Repo,
				"ref", rc.ToRef,
				"err", err,
			)
		} else {
			existing = string(raw)
		}
	}

	// Prepend the new section to any existing CHANGELOG content.
	var content string
	if existing != "" {
		content = newSection + "\n" + existing
	} else {
		content = newSection
	}

	// Upsert the file on the deterministic branch.
	if err := bc.UpsertFile(ctx, rc.Repo, branch, commitMessage, vcs.FileWrite{
		Path:    changelogPath,
		Content: []byte(content),
	}); err != nil {
		return err
	}

	// Build the PR body: hidden marker + human-readable header.
	prBody := marker + "\n\nThis PR was automatically generated by Cadoo. It updates `CHANGELOG.md` for release " + rc.ToRef + "."

	// Open or update the single PR for this release (update-else-create shape,
	// mirrors postSummary; BranchCommitter.OpenOrUpdatePR handles the
	// read-back-then-decide internally at the provider level using the
	// deterministic branch as the invariant key).
	prTitle := "chore: update CHANGELOG.md for " + rc.ToRef
	if _, err := bc.OpenOrUpdatePR(ctx, rc.Repo, branch, prBase, prTitle, prBody); err != nil {
		return err
	}

	return nil
}
