package apidocs

// oom_test.go verifies the OOM guard (T-03-04, WR-04): specs larger than
// maxSpecSize must be rejected by loadSpec before any parsing occurs.
//
// The oversized input is generated programmatically with bytes.Repeat so that
// no multi-megabyte fixture blob needs to be committed to the repository
// (WR-05: the testdata/oversized.yaml blob has been removed).

import (
	"bytes"
	"strings"
	"testing"
)

// TestLoadSpec_OOMGuard_Oversized verifies that a spec larger than maxSpecSize
// (5 MiB) is rejected by loadSpec with a non-nil error and produces no model.
//
// The test generates the oversized input with bytes.Repeat to avoid committing
// a multi-MB binary fixture (WR-05). The generated bytes form a syntactically
// valid YAML mapping that would parse successfully if the OOM guard were absent,
// so any acceptance would be a guard regression rather than a parse error.
func TestLoadSpec_OOMGuard_Oversized(t *testing.T) {
	t.Parallel()

	// Generate a spec that is maxSpecSize+1 bytes — the guard is strict
	// (len > maxSpecSize), so exactly maxSpecSize must pass and maxSpecSize+1
	// must fail (see TestLoadSpec_OOMGuard_Boundary for the boundary case).
	//
	// "a: b\n" is 5 bytes; repeat enough times to exceed maxSpecSize by at
	// least 1 byte.  The result is a valid YAML document (repeated key
	// overrides are accepted by yaml.v3) so the rejection must come from the
	// size guard, not from a parse error.
	unit := []byte("a: b\n")
	count := (maxSpecSize / len(unit)) + 1
	oversized := bytes.Repeat(unit, count)

	if len(oversized) <= maxSpecSize {
		t.Fatalf("test setup error: generated %d bytes, need > %d", len(oversized), maxSpecSize)
	}

	model, err := loadSpec(oversized)
	if err == nil {
		t.Errorf("loadSpec: expected error for oversized spec (%d bytes > maxSpecSize %d), got nil",
			len(oversized), maxSpecSize)
	}
	if model != nil {
		t.Errorf("loadSpec: expected nil model for oversized spec, got non-nil")
	}
}

// TestLoadSpec_OOMGuard_Boundary verifies the boundary condition of the OOM
// guard: a spec of exactly maxSpecSize bytes must be accepted (not rejected).
//
// The guard uses a strict greater-than comparison (len > maxSpecSize), so a
// spec of exactly maxSpecSize bytes is within the allowed limit. This test
// asserts that boundary is not accidentally changed to >=.
//
// Note: the generated maxSpecSize-byte content is not a valid OpenAPI spec, so
// loadSpec will return an error from the parse stage — that is expected. The
// test verifies only that the error is NOT "spec too large", i.e. it made it
// past the OOM guard.
func TestLoadSpec_OOMGuard_Boundary(t *testing.T) {
	t.Parallel()

	// Build exactly maxSpecSize bytes of YAML-ish content.
	// "# " is 2 bytes; pad with '#' comments to reach exactly maxSpecSize.
	// YAML treats lines starting with '#' as comments, so the document is
	// syntactically valid YAML but not a valid OpenAPI spec — parse will fail
	// after the OOM guard passes.
	var buf bytes.Buffer
	buf.Grow(maxSpecSize)
	// Fill with '#' (comment character in YAML) padded to exactly maxSpecSize.
	for buf.Len() < maxSpecSize {
		buf.WriteByte('#')
	}
	atBoundary := buf.Bytes()

	if len(atBoundary) != maxSpecSize {
		t.Fatalf("test setup error: generated %d bytes, need exactly %d", len(atBoundary), maxSpecSize)
	}

	_, err := loadSpec(atBoundary)
	// We expect an error (not a valid spec), but it must NOT be the OOM error.
	// The OOM guard error message contains "spec too large".
	if err != nil {
		if strings.Contains(err.Error(), "spec too large") {
			t.Errorf("loadSpec: boundary spec (exactly maxSpecSize=%d bytes) was rejected by OOM guard; want it to pass the guard (guard is strict >)", maxSpecSize)
		}
		// Any other error (parse failure, validation failure) is fine — the
		// content is not a real OpenAPI spec.
	}
	// nil error at exactly maxSpecSize would also be fine (if the YAML comment
	// were a valid empty spec), but is not expected here.
}
